-- Зображення для теми «Оксигено- та сульфуровмісні органічні сполуки».
-- Кожне питання з твого списку — одне зображення з public/test-images/organic/tema3 по порядку.

ALTER TABLE questions ADD COLUMN IF NOT EXISTS image_url TEXT;

UPDATE questions SET image_url = NULL WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки');

-- Питання 1–41 з твого списку → зображення 1–41 з папки tema3 (по порядку)
UPDATE questions SET image_url = '/test-images/organic/tema3/page1_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 1;
-- «Кінцевим продуктом при нагріванні брометану з водним розчином калій гідроксиду є:» (order_index = 6) — Screenshot 2026-02-15 at 12.21.05.png.
UPDATE questions SET image_url = '/test-images/organic/tema3/Screenshot%202026-02-15%20at%2012.21.05.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 6;
UPDATE questions SET image_url = '/test-images/organic/tema3/page3_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 11;
UPDATE questions SET image_url = '/test-images/organic/tema3/page3_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 12;
UPDATE questions SET image_url = '/test-images/organic/tema3/page4_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 14;
UPDATE questions SET image_url = '/test-images/organic/tema3/page4_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 16;
UPDATE questions SET image_url = '/test-images/organic/tema3/page6_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 24;
UPDATE questions SET image_url = '/test-images/organic/tema3/page9_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 36;
UPDATE questions SET image_url = '/test-images/organic/tema3/page10_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 37;
UPDATE questions SET image_url = '/test-images/organic/tema3/page10_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 39;
UPDATE questions SET image_url = '/test-images/organic/tema3/page11_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 42;
UPDATE questions SET image_url = '/test-images/organic/tema3/page11_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 43;
UPDATE questions SET image_url = '/test-images/organic/tema3/page12_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 44;
UPDATE questions SET image_url = '/test-images/organic/tema3/page14_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 50;
UPDATE questions SET image_url = '/test-images/organic/tema3/page15_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 51;
UPDATE questions SET image_url = '/test-images/organic/tema3/page18_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 58;
UPDATE questions SET image_url = '/test-images/organic/tema3/page20_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 64;
UPDATE questions SET image_url = '/test-images/organic/tema3/page21_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 69;
UPDATE questions SET image_url = '/test-images/organic/tema3/page21_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 70;
UPDATE questions SET image_url = '/test-images/organic/tema3/page22_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 71;
-- Друге питання «Який продукт утворюється при взаємодії пропіонового альдегіду з PCl5?» (order_index = 73) — два зображення підряд (image_url через кому підтримується в UI).
UPDATE questions SET image_url = '/test-images/organic/tema3/page23_img1.png,/test-images/organic/tema3/page23_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 73;
-- Перше питання «Бензальдегід в умовах реакції Канніццаро утворює:» (order_index = 74) — схема реакції (page25_img1, бо page24_img2 у папці немає; інакше зображення «з’їжджало» в наступне питання).
UPDATE questions SET image_url = '/test-images/organic/tema3/page24_img1.png,/test-images/organic/tema3/page25_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 74;
UPDATE questions SET image_url = '/test-images/organic/tema3/page26_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 75;
UPDATE questions SET image_url = '/test-images/organic/tema3/page27_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 76;
UPDATE questions SET image_url = '/test-images/organic/tema3/page27_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 77;
UPDATE questions SET image_url = '/test-images/organic/tema3/page28_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 78;
-- «Назвіть продукт складноефірної конденсації ацетальдегіду (реакції Тищенка):» (order_index = 79) — зображення з наступного питання (було зсунуто на одне).
UPDATE questions SET image_url = '/test-images/organic/tema3/page28_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 79;
UPDATE questions SET image_url = '/test-images/organic/tema3/page29_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 81;
UPDATE questions SET image_url = '/test-images/organic/tema3/page29_img2.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 82;
UPDATE questions SET image_url = '/test-images/organic/tema3/page30_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 83;
UPDATE questions SET image_url = '/test-images/organic/tema3/page31_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 84;
UPDATE questions SET image_url = '/test-images/organic/tema3/page32_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 89;
UPDATE questions SET image_url = '/test-images/organic/tema3/page33_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 91;
-- Перше питання «Який з наведених спиртів при окисненні утворює ацетон?» (order_index = 92) — два зображення: page37_img2, page37_img3.
UPDATE questions SET image_url = '/test-images/organic/tema3/page37_img2.png,/test-images/organic/tema3/page37_img3.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 92;
-- Другий дубль «Бензальдегід в умовах реакції Канніццаро утворює:» (order_index = 94) видалено — скрипт remove-duplicate-benzaldehyde-cannizzaro.sql.
-- «Вкажіть порядок реакції розкладання ацетону:» (order_index = 95) — зображення Screenshot 2026-02-15 at 11.37.24.png.
UPDATE questions SET image_url = '/test-images/organic/tema3/Screenshot%202026-02-15%20at%2011.37.24.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 95;
UPDATE questions SET image_url = '/test-images/organic/tema3/page36_img3.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 96;
-- «Виберіть сполуку, із якої в одну стадію можна синтезувати ацетонітрил» (order_index = 97) — Screenshot 2026-02-15 at 11.44.23.png (щоб інше зображення не з’їжджало вниз).
UPDATE questions SET image_url = '/test-images/organic/tema3/Screenshot%202026-02-15%20at%2011.44.23.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 97;
-- Друге питання «Який з наведених спиртів при окисненні утворює ацетон?» (order_index = 98) — два зображення.
UPDATE questions SET image_url = '/test-images/organic/tema3/page37_img2.png,/test-images/organic/tema3/page37_img3.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 98;
-- «Виберіть сполуку, із якої в одну стадію можна синтезувати ацетонітрил CH3- C ≡ N» (order_index = 99) — без зображення.
UPDATE questions SET image_url = NULL WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 99;
-- Другий дубль «Оберіть реагент для отримання ціангідрину ацетону:» (order_index = 100) видалено — скрипт remove-duplicate-cyanohydrin.sql.
-- Дублікати 15, 94, 102, 103, 112 (пропанол-2, Канніццаро, йодиметричне, порядок розкладання ацетону) видалено — remove-duplicates-propanol-iodometric.sql.
-- Друге питання «Оберіть реагент для отримання пропанола-2 з ацетону:» (order_index = 101) — Screenshot 2026-02-15 at 12.11.38.png.
UPDATE questions SET image_url = '/test-images/organic/tema3/Screenshot%202026-02-15%20at%2012.11.38.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 101;
-- «Яка із наведених формул відповідає ацетооцтовій кислоті?» (order_index = 108) — page40_img1.
UPDATE questions SET image_url = '/test-images/organic/tema3/page40_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 108;
-- «Серед нижченаведених речовин укажіть сполуку, що не дає позитивної йодоформної проби.» (order_index = 109) — page41_img1.
UPDATE questions SET image_url = '/test-images/organic/tema3/page41_img1.png' WHERE topic_id = (SELECT t.id FROM topics t JOIN courses c ON c.id = t.course_id WHERE c.title = 'Основи знань про органічні сполуки' AND t.title = 'Оксигено- та сульфуровмісні органічні сполуки') AND order_index = 109;
