-- SQL для імпорту тесту "Delving into dreams" (Freud Dreams)
-- Згенеровано: 2025-01-07
-- Кількість питань: 10

INSERT INTO krok_questions_unified (
  question_text, year, faculty, category, difficulty,
  option_a, option_b, option_c, option_d, option_e,
  correct_answer, explanation_text, reference_text,
  test_identifier, title, created_at, updated_at
) VALUES
(
  'Freud''s relationship with his father could best be described as:',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Easygoing',
  'Loving and supportive',
  'Difficult and strained',
  'Nonexistent',
  '',
  'C',
  'Based on Freud''s autobiographical accounts and self-analysis',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'According to Freud, what are dreams primarily an expression of?',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Subconscious wishes',
  'Random thought',
  'Logical reasoning',
  'Daily experiences',
  '',
  'A',
  'Freud believed dreams were expressions of repressed unconscious desires',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'Choose the correct statement:',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Freud proposed that dreams were a way to act out repressed urges',
  'Freud considered dreams as random and meaningless experiences',
  'Freud believed dreams were unrelated to any psychological issues',
  'Freud''s Interpretation of Dreams was published in 1889',
  '',
  'A',
  'Freud''s central theory was that dreams fulfill repressed wishes',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'Freud believed that dreams were a way of:',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Fulfilling suppressed desires',
  'Solving problems',
  'Reliving past memories',
  'Experiencing reality',
  '',
  'A',
  'Dreams allow expression of repressed wishes in symbolic form',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'Freud identified a deep-seated feeling of rivalry with his father and affection for his mother, concept later known as:',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Psychosexual development',
  'Oedipus complex',
  'Electra complex',
  'Dream analysis',
  '',
  'B',
  'The Oedipus complex describes unconscious sexual desire for the opposite-sex parent',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'According to Freud, what was necessary to achieve a cure for mental health issues?',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Probing the unconscious mind',
  'Hypnotic treatment',
  'Ignoring childhood memories',
  'Medication',
  '',
  'A',
  'Freud believed accessing the unconscious was key to psychological healing',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'In Freud''s dream, what was his father''s ghost accused of?',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Inheriting money',
  'Committing a crime',
  'Getting intoxicated and being held',
  'Leaving the family',
  '',
  'C',
  'Freud''s dream revealed his father''s past drinking and detention',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'Freud''s theory emphasized that traumatic incidents during what period of life could lead to mental issues in adulthood?',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Middle age',
  'Childhood',
  'Adolescence',
  'Old age',
  '',
  'B',
  'Freud believed childhood trauma was the root of adult psychological problems',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'Freud considered dreams to be:',
  2025,
  'medical',
  'Psychology',
  'medium',
  'Unrelated to any emotions',
  'A gateway to understanding the unconscious',
  'A reflection of conscious thoughts',
  'An escape from reality',
  '',
  'B',
  'Dreams provide access to the unconscious mind and repressed content',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
),
(
  'What event led Freud to start his self-examination through dreams?',
  2025,
  'medical',
  'Psychology',
  'medium',
  'The birth of his first child',
  'His marriage',
  'A severe illness',
  'The death of his father',
  '',
  'D',
  'Freud began self-analysis after his father''s death in 1896',
  'Freud, S. (1899). The Interpretation of Dreams',
  '2025-freud-dreams',
  'Delving into dreams',
  NOW(),
  NOW()
);

-- Перевірка кількості доданих записів
SELECT COUNT(*) as freud_dreams_questions FROM krok_questions_unified WHERE test_identifier = '2025-freud-dreams';
